/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votingsystem.Forms;

import java.awt.Color;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Account;
import model.DBConnection;
import model.Department;
import model.Election;
import model.PartyList;

/**
 *
 * @author jerome
 */
public class ControlPanel extends javax.swing.JFrame {

    /**
     * Creates new form ControlPanel
     */
    
    ArrayList<Election> electionList = null;
    private Account account;
    private LoginForm loginForm;
    public ControlPanel(LoginForm loginForm, Account account) {
        this.loginForm = loginForm;
        this.account = account;
        initComponents();
        
        this.setTitle("Admin Panel");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        startElectionBtn = new javax.swing.JButton();
        stopElectionBtn = new javax.swing.JButton();
        label1 = new java.awt.Label();
        managePartyListBtn = new javax.swing.JButton();
        createElectionBtn = new javax.swing.JButton();
        electionComboBox = new javax.swing.JComboBox<Election>();
        statusField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        deleteElectionBtn = new javax.swing.JButton();
        resultBtn = new javax.swing.JButton();
        ArrayList<Department> departmentList = Department.getAll();
        departmentComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        leaderboardBtn = new javax.swing.JButton();

        jDialog1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDialog1KeyPressed(evt);
            }
        });

        jButton7.setText("jButton7");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jButton7)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jButton7)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jButton6.setText("jButton6");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        startElectionBtn.setText("Start Election");
        startElectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startElectionBtnActionPerformed(evt);
            }
        });

        stopElectionBtn.setText("Stop Election");
        stopElectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopElectionBtnActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label1.setText("Select Election");

        managePartyListBtn.setText("Manage Partylist");
        managePartyListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePartyListBtnActionPerformed(evt);
            }
        });

        createElectionBtn.setText("Create Election");
        createElectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createElectionBtnActionPerformed(evt);
            }
        });

        electionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electionComboBoxActionPerformed(evt);
            }
        });

        statusField.setEditable(false);
        statusField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        statusField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        statusField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Status");

        deleteElectionBtn.setText("Delete Election");
        deleteElectionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteElectionBtnActionPerformed(evt);
            }
        });

        resultBtn.setText("View Result");
        resultBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultBtnActionPerformed(evt);
            }
        });

        departmentComboBox.setModel(new DefaultComboBoxModel(departmentList.toArray()));
        departmentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Select Department");

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        leaderboardBtn.setText("View Leaderboard");
        leaderboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderboardBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(departmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(leaderboardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(startElectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(stopElectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(createElectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(resultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(managePartyListBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(deleteElectionBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(electionComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departmentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(electionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(leaderboardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startElectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopElectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(managePartyListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createElectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteElectionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(logoutBtn)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Control Panel", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stopElectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopElectionBtnActionPerformed
            // TODO add your handling code here:
            Department department = (Department) departmentComboBox.getSelectedItem();
            Election election = (Election) electionComboBox.getSelectedItem();
            if(election != null && department != null) {
                if(JOptionPane.showConfirmDialog(this, "Are you sure you want to stop?") == 0) {
                    String updateElection = "UPDATE election SET status = 'INACTIVE' WHERE id = " + election.getId();
                    if(DBConnection.updateQuery(updateElection) > 0) {
                        int selectedIndex = electionComboBox.getSelectedIndex();
                        JOptionPane.showMessageDialog(this, election.getName() + " is now INACTIVE");
                        electionList = Election.getElectionUsingDepartmentId(department.getId());
                        electionComboBox.setModel(new DefaultComboBoxModel(electionList.toArray()));
                        electionComboBox.setSelectedIndex(selectedIndex);
                        statusField.setText("INACTIVE");
                        statusField.setForeground(Color.RED);
                        managePartyListBtn.setEnabled(false);
                        resultBtn.setEnabled(true);
                    }else {
                        JOptionPane.showMessageDialog(this, "Error");
                    }
                }
            }
    }//GEN-LAST:event_stopElectionBtnActionPerformed

    private void jDialog1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDialog1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDialog1KeyPressed

    private void createElectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createElectionBtnActionPerformed
        // TODO add your handling code here:
        
//        String electionName = JOptionPane.showInputDialog(rootPane, "Election name: ", null);
//        
//        if(electionName == null || electionName.isEmpty()){ 
//            JOptionPane.showMessageDialog(this, "Empty field");
//            return;
//        }else if(!Election.isAvailable(electionName)) {
//            JOptionPane.showMessageDialog(this, "Election name already exist");
//            return;
//        }else {
//            if(Election.insert(electionName) > 0) {
//                JOptionPane.showMessageDialog(this, "Succesfully inserted");
//                reloadPage();
//                return;
//            }
//        }
//        Department department = (Department) departmentComboBox.getSelectedItem();
        AddElectionForm electionForm = new AddElectionForm(this);
        electionForm.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_createElectionBtnActionPerformed
 
    private void managePartyListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePartyListBtnActionPerformed
        // TODO add your handling code here:
        Election election = (Election) electionComboBox.getSelectedItem();
        if(election != null) {
            PartyListForm partylist = new PartyListForm(election, this);
            this.setVisible(false);
            partylist.setVisible(true);
        }
    }//GEN-LAST:event_managePartyListBtnActionPerformed

    private void electionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electionComboBoxActionPerformed
        // TODO add your handling code here:
        Election election = (Election) electionComboBox.getSelectedItem();
        if(election.getStatus().equals("ACTIVE")) {
            statusField.setForeground(Color.GREEN);
            statusField.setText(election.getStatus());
            managePartyListBtn.setEnabled(true);
        }else if(election.getStatus().equals("INACTIVE")) {
            statusField.setForeground(Color.RED);
            statusField.setText(election.getStatus());
            managePartyListBtn.setEnabled(false);
        }
    }//GEN-LAST:event_electionComboBoxActionPerformed

    private void startElectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startElectionBtnActionPerformed
        // TODO add your handling code here:
        Election election = (Election) electionComboBox.getSelectedItem();
        Department department = (Department) departmentComboBox.getSelectedItem();
        String updateElection = "UPDATE election SET status = 'ACTIVE' WHERE id = " + election.getId();
        if(election != null && department != null) {
            if(DBConnection.updateQuery(updateElection) > 0) {
                int selectedIndex = electionComboBox.getSelectedIndex();
                JOptionPane.showMessageDialog(this, election.getName() + " is now ACTIVE");
                electionList = Election.getElectionUsingDepartmentId(department.getId());
                electionComboBox.setModel(new DefaultComboBoxModel(electionList.toArray()));
                electionComboBox.setSelectedIndex(selectedIndex);
                statusField.setText("ACTIVE");
                statusField.setForeground(Color.GREEN);
                managePartyListBtn.setEnabled(true);
            }else {
                JOptionPane.showMessageDialog(this, "Error");
            }
        }
        
    }//GEN-LAST:event_startElectionBtnActionPerformed

    private void statusFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusFieldActionPerformed

    private void deleteElectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteElectionBtnActionPerformed
        // TODO add your handling code here:
        
        Election election = (Election) electionComboBox.getSelectedItem();
        Department department = (Department) departmentComboBox.getSelectedItem();
        if(election != null && department != null) {
            if(JOptionPane.showConfirmDialog(this,"Are you sure?") == 0) { 

                if(Election.delete(election.getId())) {
                    reloadElectionComboBox(department.getId());
                    reloadPage();
                    JOptionPane.showMessageDialog(this, "Succesfully Deleted");
                }
            }
        }
    }//GEN-LAST:event_deleteElectionBtnActionPerformed

    private void departmentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentComboBoxActionPerformed
        // TODO add your handling code here:
        Department department = (Department) departmentComboBox.getSelectedItem();
        reloadElectionComboBox(department.getId());
        reloadPage();
    }//GEN-LAST:event_departmentComboBoxActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Are you sure you want to log out?") == 0) {
            this.dispose();
            this.loginForm.setVisible(true);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void resultBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultBtnActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_resultBtnActionPerformed

    private void leaderboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderboardBtnActionPerformed
        // TODO add your handling code here:
        
        Election election = (Election) electionComboBox.getSelectedItem();
        Leaderboard leaderboard = new Leaderboard(this, election);
        leaderboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_leaderboardBtnActionPerformed
    
    public void reloadElectionComboBox(int departmentId) {
        this.electionList = Election.getElectionUsingDepartmentId(departmentId);
        electionComboBox.setModel(new DefaultComboBoxModel(this.electionList.toArray()));
        
    }
    private void reloadPage() {
        
        Election election = (Election) electionComboBox.getSelectedItem();
        //reload combo box
        if(election != null) {
            if(election.getStatus().equals("ACTIVE")) {
                statusField.setForeground(Color.GREEN);
                statusField.setText(election.getStatus());
                managePartyListBtn.setEnabled(true);
                resultBtn.setEnabled(false);
                return;
            }else if(election.getStatus().equals("INACTIVE")) {
                statusField.setForeground(Color.RED);
                statusField.setText(election.getStatus());
                managePartyListBtn.setEnabled(false);
                resultBtn.setEnabled(true);
                return;
            }
        }
        resultBtn.setEnabled(false);
        managePartyListBtn.setEnabled(false);
        
        statusField.setText("");    
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ControlPanel().setVisible(true);
//            }
//        });
//    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createElectionBtn;
    private javax.swing.JButton deleteElectionBtn;
    private javax.swing.JComboBox<String> departmentComboBox;
    private javax.swing.JComboBox<Election> electionComboBox;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private java.awt.Label label1;
    private javax.swing.JButton leaderboardBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton managePartyListBtn;
    private javax.swing.JButton resultBtn;
    private javax.swing.JButton startElectionBtn;
    private javax.swing.JTextField statusField;
    private javax.swing.JButton stopElectionBtn;
    // End of variables declaration//GEN-END:variables
}
