/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votingsystem.Forms;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Account;
import model.Candidate;
import model.Constant;
import model.Department;
import model.Election;
import model.Vote;

/**
 *
 * @author jerome
 */
public class VoteForm extends javax.swing.JFrame {

    /**
     * Creates new form VoteForm
     */
//    position index in mysql
    
    
    
    private Account account;
    private UserPanel userPanel;
    private Election election;
    
    public VoteForm(UserPanel userPanel, Account account, Election election) {
        this.userPanel = userPanel;
        this.account = account;
        this.election = election;
        initComponents();
        
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        studentNoLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        departmentLabel = new javax.swing.JLabel();
        electionLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ArrayList<Candidate> runningVicePresident = Candidate.getCandidateUsingElectionIdAndPositionId(election.getId(),Constant.VICEPRESIDENT_ID);
        vicePresidentComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ArrayList<Candidate> runningAuditor = Candidate.getCandidateUsingElectionIdAndPositionId(election.getId(), Constant.AUDITOR_ID);
        auditorComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ArrayList<Candidate> runningTreasurer = Candidate.getCandidateUsingElectionIdAndPositionId(election.getId(), Constant.TREASURER_ID);
        treasurerComboBox = new javax.swing.JComboBox<>();
        ArrayList<Candidate> runningPIO = Candidate.getCandidateUsingElectionIdAndPositionId(election.getId(), Constant.PIO_ID);
        pioComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        ArrayList<Candidate> runningPeaceOfficer = Candidate.getCandidateUsingElectionIdAndPositionId(election.getId(), Constant.PEACEOFFICER_ID);
        peaceOfficerComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        ArrayList<Candidate> runningPresidents = Candidate.getCandidateUsingElectionIdAndPositionId(election.getId(), Constant.PRESIDENT_ID);
        presidentComboBox = new javax.swing.JComboBox<>();
        ArrayList<Candidate> runningSecretary = Candidate.getCandidateUsingElectionIdAndPositionId(election.getId(),Constant.SECRETARY_ID);
        secretaryComboBox = new javax.swing.JComboBox<>();
        submitVoteBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ballot form");

        studentNoLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        studentNoLabel.setText("Student No: " + this.account.getStudentNo());

        nameLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nameLabel.setText("Name: " + this.account.getFullName());

        departmentLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        departmentLabel.setText("Department: " + Department.getName(this.account.getDepartmentId()));

        electionLabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        electionLabel.setText("Election: " + this.election.getName());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("President");

        vicePresidentComboBox.setModel(new DefaultComboBoxModel(runningVicePresident.toArray()));
        vicePresidentComboBox.setSelectedIndex(-1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Vice-President");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Secretary");

        auditorComboBox.setModel(new DefaultComboBoxModel(runningAuditor.toArray()));
        auditorComboBox.setSelectedIndex(-1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Auditor");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Treasurer");

        treasurerComboBox.setModel(new DefaultComboBoxModel(runningTreasurer.toArray()));
        treasurerComboBox.setSelectedIndex(-1);

        pioComboBox.setModel(new DefaultComboBoxModel(runningPIO.toArray()));
        pioComboBox.setSelectedIndex(-1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("PIO");

        peaceOfficerComboBox.setModel(new DefaultComboBoxModel(runningPeaceOfficer.toArray()));
        peaceOfficerComboBox.setSelectedIndex(-1);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Peace Officer");

        presidentComboBox.setModel(new DefaultComboBoxModel(runningPresidents.toArray()));
        presidentComboBox.setSelectedIndex(-1);

        secretaryComboBox.setModel(new DefaultComboBoxModel(runningSecretary.toArray()));
        secretaryComboBox.setSelectedIndex(-1);

        submitVoteBtn.setText("Submit Vote");
        submitVoteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitVoteBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(electionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                                            .addComponent(departmentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(studentNoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(submitVoteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(auditorComboBox, 0, 279, Short.MAX_VALUE)
                                                    .addComponent(treasurerComboBox, 0, 279, Short.MAX_VALUE)
                                                    .addComponent(pioComboBox, 0, 279, Short.MAX_VALUE)
                                                    .addComponent(peaceOfficerComboBox, 0, 279, Short.MAX_VALUE)
                                                    .addComponent(vicePresidentComboBox, 0, 279, Short.MAX_VALUE)
                                                    .addComponent(presidentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(secretaryComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(292, 292, 292))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentNoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(departmentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(electionLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(presidentComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vicePresidentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(secretaryComboBox))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(auditorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(treasurerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pioComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peaceOfficerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitVoteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitVoteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitVoteBtnActionPerformed
        // TODO add your handling code here:
        ArrayList<String> errors = new ArrayList<>();
        
        Candidate president = (Candidate) presidentComboBox.getSelectedItem();
        Candidate vicePresident = (Candidate) vicePresidentComboBox.getSelectedItem();
        Candidate secretary = (Candidate) secretaryComboBox.getSelectedItem();
        Candidate auditor = (Candidate) auditorComboBox.getSelectedItem();
        Candidate treasurer = (Candidate) treasurerComboBox.getSelectedItem();
        Candidate pio = (Candidate) pioComboBox.getSelectedItem();
        Candidate peaceOfficer = (Candidate) peaceOfficerComboBox.getSelectedItem();
        
        if(president == null) {
            errors.add("Choose president");
        }
        
        if(vicePresident == null) {
            errors.add("Choose vice-president");
        }
        
        if(secretary == null) {
            errors.add("Choose secretary");
        }
        
        if(auditor == null) {
            errors.add("Choose auditor");
        }
        
        if(treasurer == null) {
            errors.add("Choose treasurer");
        }
        
        if(pio == null) {
            errors.add("Choose pio");
        }
        
        if(peaceOfficer == null) {
            errors.add("Choose peace officer");
        }
        
        if(errors.size() > 0) {
            JOptionPane.showMessageDialog(this, errors.toArray());
        }else {
            if(!Vote.already(this.account.getId(), this.election.getId())) {
                Candidate.incrementVoteCount(president.getId());
                Candidate.incrementVoteCount(vicePresident.getId());
                Candidate.incrementVoteCount(secretary.getId());
                Candidate.incrementVoteCount(auditor.getId());
                Candidate.incrementVoteCount(treasurer.getId());
                Candidate.incrementVoteCount(pio.getId());
                Candidate.incrementVoteCount(peaceOfficer.getId());
                
                    if(Vote.markAccountAsVoted(this.account.getId(), this.election.getId()) > 0) {
                        JOptionPane.showMessageDialog(this, "Thankyou for voting.");
                        this.dispose();
                        this.userPanel.setVisible(true);
                        return;
                    }
                
            }else {
                    JOptionPane.showMessageDialog(this, "You already voted");
                    return;
            }
        }
        
        
    }//GEN-LAST:event_submitVoteBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.userPanel.setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> auditorComboBox;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel departmentLabel;
    private javax.swing.JLabel electionLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JComboBox<String> peaceOfficerComboBox;
    private javax.swing.JComboBox<String> pioComboBox;
    private javax.swing.JComboBox<String> presidentComboBox;
    private javax.swing.JComboBox<String> secretaryComboBox;
    private javax.swing.JLabel studentNoLabel;
    private javax.swing.JButton submitVoteBtn;
    private javax.swing.JComboBox<String> treasurerComboBox;
    private javax.swing.JComboBox<String> vicePresidentComboBox;
    // End of variables declaration//GEN-END:variables
}
